import type { Metadata } from 'next'
import './globals.css'
import SessionWrapper from './components/SessionWrapper'
import localFont from 'next/font/local'


const myFont = localFont({
  src: '../public/fonts/AppleSDGothicNeoEB.ttf',
  display: 'swap',
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SessionWrapper >
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
    </SessionWrapper>
  )
}